// Edit this file to personalize your portfolio. No other file needs to change.

export const profile = {
  name: 'Arul Jeffry A',
  title: 'Electrical & Electronics Engineering Student',
  tagline:
    'Final-year EEE undergraduate specializing in power electronics, power conversion, closed-loop control, multi-layer PCB design (KiCad), and embedded firmware on TI C2000 microcontrollers.',
  location: 'Tiruchirappalli / Tirunelveli, Tamil Nadu, India',
  avatarInitials: 'AJ',
  resumeUrl: '/files/resume.pdf',
}

export const about = {
  paragraphs: [
    "I'm a final-year Electrical and Electronics Engineering undergraduate (2027 batch, SASTRA Deemed University, Smart Grid and Electric Vehicles specialization) with hands-on experience in power electronics, power conversion, closed-loop control, multi-layer PCB design using KiCad, and embedded firmware development on TI C2000 microcontrollers.",
    "I'm looking for a Graduate Engineer Trainee (GET) or Project Engineer role where I can contribute to power conversion system design, circuit design, hardware debugging, and embedded control for industrial and electrification applications.",
    "Recently, I completed an Electrical Engineering internship at TANGEDCO (Tamil Nadu Generation and Distribution Corporation Limited), Trichy Electricity Distribution Circle, where I studied energy metering, protection equipment (CTs, PTs, relays, circuit breakers), and substation SCADA monitoring.",
  ],
}

export const skills = [
  {
    category: 'Power Electronics',
    items: ['Buck / SIMO DC-DC Converters', 'PWM Generation', 'PI Closed-Loop Control', 'Power Conversion System Design'],
  },
  {
    category: 'Microcontrollers & Embedded',
    items: ['TI C2000 (F280049C, F28069)', 'STM32F103C8T6', 'Embedded C', 'ADC/DAC, ePWM, I²C, SPI'],
  },
  {
    category: 'PCB Design & Fabrication',
    items: ['KiCad', 'Multi-layer PCB Layout', 'Power/Ground Planes', 'DRC, Gerber/BOM Generation', 'Fabrication & Soldering'],
  },
  {
    category: 'Power Systems',
    items: ['Energy Metering', 'Protection Equipment (CTs, PTs, Relays)', 'Substation & SCADA Monitoring'],
  },
  {
    category: 'Development Tools',
    items: ['MATLAB / Simulink', 'Code Composer Studio', 'STM32CubeIDE'],
  },
  {
    category: 'Programming Languages',
    items: ['C', 'C++', 'Python'],
  },
]

export const projects = [
  {
    title: 'SIMO DC-DC Buck Converter — Design & Simulation',
    description:
      'Designed a six-switch, five-inductor Single Input Multiple Output (SIMO) buck converter generating regulated 18.5V, 15V, 12V, 5V, and 3.3V outputs from a 48V DC input. Led duty-cycle, inductance, and capacitance calculations for Continuous Conduction Mode with a 0.02% output-ripple target, and built the MATLAB/Simulink model with PI closed-loop control and NAND-based switching logic.',
    tags: ['MATLAB/Simulink', 'Power Electronics', 'PI Control'],
    link: '',
    repo: '',
    report: '/files/simo-buck-converter-report.pdf',
  },
  {
    title: 'Synchronous Buck Converter — TT Motor Drive (TI C2000)',
    description:
      'Designed and implemented an open-loop synchronous buck converter to step down 12V DC to 5V DC for driving a TT motor. Two MOSFETs were switched via an IR2104 gate driver with complementary PWM signals generated by a TI C2000 microcontroller, with the design fabricated as a working PCB and verified through simulation and hardware testing.',
    tags: ['TI C2000', 'Embedded C', 'KiCad', 'PCB Fabrication'],
    link: '',
    repo: '',
    report: '/files/tt-motor-buck-converter-report.pdf',
  },
  {
    title: 'LAUNCHXL-F280049C — Four-Layer PCB Design',
    description:
      'Designed a four-layer TI C2000 LaunchPad PCB in KiCad, including power/ground planes, component placement, and routing. Ran Design Rule Checks and generated Gerber, drill, and BOM files for fabrication.',
    tags: ['KiCad', 'PCB Design', 'TI C2000'],
    link: '',
    repo: '',
  },
  {
    title: 'STM32F103C8T6 — Two-Layer PCB Design',
    description:
      'Designed a two-layer STM32F103C8T6 PCB with schematic capture, ground pour, and routing. Ran Design Rule Checks and generated Gerber files for fabrication.',
    tags: ['KiCad', 'PCB Design', 'STM32'],
    link: '',
    repo: '',
  },
]

export const contact = {
  email: 'aruljeffry.2005a@gmail.com',
  phone: '+91-8754534022',
  github: '',
  linkedin: 'https://linkedin.com/in/arul-jeffry-a-3489b7300',
  twitter: '',
}
